spring:
  profiles:
    active: dev   #选dev中的配置
server:
  servlet:
    context-path: /xyxblog

---
server:
  port: 8081
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xyxblog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: memory # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    auto-startup: true # Quartz 是否自动启动
    startup-delay: 0 # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: false # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: true # 是否覆盖已有 Job 的配置
    properties: # 添加 Quartz Scheduler 附加属性
      org:
        quartz:
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
mybatis:
  type-aliases-package: com.hfut.xyxblog.dao.Entity
  mapper-locations: classpath:mapperXML/*.xml
  configuration:
    map-underscore-to-camel-case: true
#pagehelper分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#日志设置
logging:
  #level 日志等级 指定命名空间的日志输出
  level:
    root: info
  #file 指定输出文件的存储路径
  file:
    name: logs/app.log

---
server:
  port: 8082
spring:
  profiles: test

---
server:
  port: 8088
spring:
  profiles: prod